[project]
name = "kotlinds"
version = "0.1.0"
description = ""
authors = [
    {name = "Dave Musicant",email = "dmusicant@carleton.edu"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pretext (>=2.32.0,<3.0.0)",
    "matplotlib (>=3.10.7,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
