fun main() {
    val g = AdjacencyListGraph<String>()
    g.addEdge("A", "B")
    g.addEdge("A", "D")
    g.addEdge("B", "C")
    g.addEdge("B", "D")
    g.addEdge("D", "E")
    g.addEdge("E", "B")
    g.addEdge("E", "F")
    g.addEdge("F", "C")
    g.addEdge("G", "H")
    val dfsSolver = DfsSolver(g, "A")
    println(dfsSolver.previous)
    println(dfsSolver.closingTime)
}